# Generated by Django 6.0.1 on 2026-01-08 01:19

import django.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('user', 'Usuario'), ('grupo', 'Grupo'), ('sala', 'Sala')], max_length=10)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo_postal', models.CharField(blank=True, max_length=10, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('id_usuario', models.UUIDField(default=django.db.models.fields.UUIDField, editable=False, primary_key=True, serialize=False)),
                ('dni', models.CharField(blank=True, max_length=9, null=True, unique=True)),
                ('cif', models.CharField(blank=True, max_length=10, null=True, unique=True)),
            ],
        ),
    ]
